services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - "./:/usr/src/app"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    env_file:
      - .env


  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
volumes:
  redis-data: